#!/usr/bin/env bash

##################################################
#### Wipe device and partition it with several same-sized partitions
##################################################

##################################################
#### partname is not optional, the way this script invokes parted
#### I could not get parted, in script mode, to parse args better
#### partitions all created as primary, which is fine with gpt
#### specifying too many or too large partions results in fewer created

partcount=16
partgb=32
partname=iscsi
device=/dev/nvme0n1zzz


read -r -n 1 -s -p "Press any key to wipe ${device} and partition with ${partcount} new ${partgb}GiB partitions "
echo
[[ -b "${device}" ]] || { echo "${device} invalid"; exit 1; }
echo -n "Continuing in a few seconds..."
for i in {1..3}; do sleep "${i}"; echo -n .; done; echo

for i in $(lsblk -l ${device} | tail -n+3 | cut -d' ' -f1); do wipefs -a /dev/"${i}" &> /dev/null; done &&
wipefs -a ${device} &> /dev/null &&
parted --align=optimal ${device} --script -- \
$(echo "'mklabel gpt'") \
$(echo "'mkpart ${partname} 0% ${partgb}GiB'") \
$(for i in $(seq 1 $(("${partcount}"-1))); do
echo -e "'mkpart ${partname} $(( $i*${partgb} ))GiB $(( $i*${partgb}+${partgb} ))GiB'"
done) &&
parted --align=optimal ${device} p
